<!-- Start of SkyGlue Code -->
<script type="text/javascript">
    var _sgq = _sgq || [];
    _sgq.push(['setSgAccount', '<?php echo Mage::getStoreConfig('skyglue_options/settings/sgaccount');?>']);

    setTimeout(function() {
        var sg = document.createElement('script'); sg.type = 'text/javascript'; sg.async = true;
        sg.src = ("https:" == document.location.protocol ? "https://dc" : "http://cdn0") + ".skyglue.com/sgtracker.js";
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sg, s);
    }, 1);
</script>
<!-- End of SkyGlue Code -->

<?php if (Mage::getSingleton('customer/session')->isLoggedIn()):?>
    <script type="text/javascript">
        var _sg_registeredUserId = "<?php echo Mage::helper('customer')->getCustomer()->getId();?>";
    </script>
<?php endif ?>